### ISSUE TITLE
warn only if file specified with '-a' parameter is missing

### ISSUE THREAD

**Issue by k2s** [okraits/j4-make-config#10]
current situation is that if I execute ``j4-make-config -a custom.conf`` it will fail with exception

could you pls. change it to only raise warning that the file is missing ?

Maybe by adding test condition [here](https://github.com/okraits/j4-make-config/blob/master/j4-make-config#L128)

**Comment by okraits** [comment]
This is what i tried to reproduce your issue:

okraits@asterix ~ $ j4-make-config -a customconf archlinux
Error: file customconf could not be opened.

Am i correct that you basically want j4-make-config to generate the config file without appending the specified but missing file and just show a warning instead of stop the execution?

**Comment by k2s** [comment]
yes, exactly as you summarized

I am sharing i3 config between multiple PCs and want to be able to do small adjustements in `customconf`. It would be easier to achieve if `j4-make-config` would handle if that file is missing.

thank you

**Comment by okraits** [comment]
Why don't you omit the -a argument on the PCs where you don't have the file customconf? j4-make-config stores the previously used arguments in ~/.j4-make-config.rc so you can use the argument once and then simply run j4-make-config the next time to use the previous arguments again.
